apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  sources:
    - path: charts/kube-prometheus-stack
      repoURL: ssh://git@100.127.255.11:2222/jaken/xcharts.git
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
    - path: .
      repoURL: https://github.com/dotdc/grafana-dashboards-kubernetes
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true