apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: charts/kube-prometheus-stack
    repoURL: ssh://git@100.127.255.11:2222/jaken/xcharts.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true