namespace: monitoring

prometheus:
  image: prom/prometheus:v2.44.0
  retention: 200h
  storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  extraScrapeConfigs: []
  #  - job_name: node-exporter
  #    static_configs:
  #      - targets: ["100.127.255.146:9100"]
  #        labels: {instance: "shippo"}

grafana:
  image: grafana/grafana-oss:10.4.2
  storage: 10Gi
  adminUser: jaken
  adminPassword: rin
  anonymous:
    enabled: true
    orgName: "Main Org."
    orgRole: Viewer

ksm:
  image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: prometheus.ayu.local
      service: prometheus
      port: 9090
    - host: prometheus.xx.local
      service: prometheus
      port: 9090
    - host: grafana.ayu.local
      service: grafana
      port: 3000
    - host: grafana.xx.local
      service: grafana
      port: 3000
    - host: monitor.rurutia.net
      service: grafana
      port: 3000