namespace: monitor

prometheus:
  image: prom/prometheus:v2.44.0
  retention: 200h
  storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 2Gi
  hostNetwork: false
  extraScrapeConfigs:
    - job_name: node-exporter
      static_configs:
        - targets: ["100.127.255.146:9100"]
          labels: {instance: "shippo"}
        - targets: ["100.127.255.243:9100"]
          labels: {instance: "tunnel"}
        - targets: ["100.127.255.48:9100"]
          labels: {instance: "spy"}
        - targets: ["100.127.255.11:9100"]
          labels: {instance: "xx"}
        - targets: ["100.127.255.1:9100"]
          labels: {instance: "ayu"}
        - targets: ["100.127.255.101:9100"]
          labels: {instance: "entropy"}
        - targets: ["100.127.255.32:9100"]
          labels: {instance: "reserve"}
    - job_name: frps
      metrics_path: /metrics
      scheme: https
      static_configs:
        - targets: ["dashboard.x.caix.top:443"]
          labels: {instance: "frps-cx"}
      basic_auth:
        username: jaken
        password: kubernetes
    - job_name: jenkins
      metrics_path: /prometheus/
      static_configs:
        - targets: ["100.127.255.11:18080"]
          labels: {instance: "jenkins-xx"}
    - job_name: gitea
      static_configs:
        - targets: ["100.127.255.11:8001"]
          labels: {instance: "gitea-xx"}
    - job_name: argocd
      static_configs:
        - targets: ["argocd-application-controller-metrics.argocd.svc.cluster.local:8082"]
          labels: {instance: "argocd-xx"}

grafana:
  image: grafana/grafana-oss:10.4.2
  storage: 10Gi
  adminUser: jaken
  adminPassword: rin
  anonymous:
    enabled: true
    orgName: "Main Org."
    orgRole: Viewer

ksm:
  image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: prometheus.ayu.local
      service: prometheus
      port: 9090
    - host: prometheus.xx.local
      service: prometheus
      port: 9090
    - host: grafana.ayu.local
      service: grafana
      port: 3000
    - host: grafana.xx.local
      service: grafana
      port: 3000
    - host: monitor.rurutia.net
      service: grafana
      port: 3000