namespace: monitor

prometheus:
  image: prom/prometheus:v2.44.0
  retention: 200h
  storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  extraScrapeConfigs: []
  hostNetwork: false

grafana:
  image: grafana/grafana-oss:10.4.2
  storage: 10Gi
  adminUser: admin
  adminPassword: admin
  anonymous:
    enabled: true
    orgName: "Main Org."
    orgRole: Viewer

ksm:
  image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0

ingress:
  enabled: false
  className: nginx
  hosts: []