apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: config
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.15.1
    helm:
      values: |-
        controller:
          service:
            type: LoadBalancer
          ingressClassResource:
            name: nginx
            default: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true