apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: config
  source:
    path: charts/metallb
    repoURL: ssh://git@172.31.0.11:2222/jaken/xcharts.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true